version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:stable
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql
      - api
      - frontend
      - backend
      - memcached
    ports:
      - 80:80

  api:
    container_name: api
    image: $REGISTRY_DOMAIN/chrisleekr/yii2-angular-boilerplate:api-dev
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - COOKIE_VALIDATION_KEY=K0I9yOJPLBqbaam4I
      - PHP_ENABLE_XDEBUG=0
      - YII_ENV_DEV=1
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=boilerplate
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - CACHE_USE_MEMCACHED=true
      - CACHE_SERVERS=memcached
      - CACHE_PORT=11211
      - CACHE_WEIGHT=60
      - CACHE_USERNAME=
      - CACHE_PASSWORD=
            
  backend:
    container_name: backend
    image: $REGISTRY_DOMAIN/chrisleekr/yii2-angular-boilerplate:backend-dev
    depends_on:
      - api
    networks:
      - internal
    command: ["nginx", "-g", "daemon off;"]

  frontend:
    container_name: frontend
    image: $REGISTRY_DOMAIN/chrisleekr/yii2-angular-boilerplate:frontend-dev
    depends_on:
      - api
    networks:
      - internal
    command: ["nginx", "-g", "daemon off;"]

  memcached:
    container_name: memcached
    image: memcached:latest
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=boilerplate
      - TZ=Australia/Melbourne

networks:
  internal:
    driver: bridge

